version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DATABASE_URL: file:/app/prisma/prisma/dev.db 
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "80:5173"
    depends_on:
      - backend
